version: "3.9"
services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      regis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      prometheus:
        condition: service_started

  regis:
    image: redis
    command: redis-server --requirepass Redis2022!
    hostname: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 30

  postgres:
    image: postgres
    ports:
      - 5432:5432
    user: postgres
    environment:
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 30

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    hostname: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    user: '1000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    hostname: grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana

